### ISSUE TITLE
Decrement??

### ISSUE THREAD

**Issue by flypenguin** [p3lim/increment-selection#5]
Love it, unfortunately for me it's completely useless without decrement. I know that things should only go up, and higher, and higher, and shit, but sometimes you gotta come back down to earth, right? :)

so decrement would be a real kicker!!

**Comment by p3lim** [comment]
I don't use Atom any more (performance reasons), but if you send me a patch I'll add support for it.

**Comment by flypenguin** [comment]
back to sublime? :) or VS code? okay, I'll see what I can do. probably not so much - work and JS noob ... but it'd be nice to try :D

**Comment by p3lim** [comment]
Sublime, anything using webkit just can't compare.
